In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [10]:
voc_size=10000

In [11]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3914, 2091, 1835, 8363],
 [3914, 2091, 1835, 8185],
 [3914, 3360, 1835, 6167],
 [2141, 9390, 331, 1941, 4362],
 [2141, 9390, 331, 1941, 2480],
 [4460, 3914, 828, 1835, 5995],
 [4478, 6243, 6943, 1941]]

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [15]:

sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3914 2091 1835 8363]
 [   0    0    0    0 3914 2091 1835 8185]
 [   0    0    0    0 3914 3360 1835 6167]
 [   0    0    0 2141 9390  331 1941 4362]
 [   0    0    0 2141 9390  331 1941 2480]
 [   0    0    0 4460 3914  828 1835 5995]
 [   0    0    0    0 4478 6243 6943 1941]]


In [16]:
dim = 10

In [26]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[-0.03711472, -0.03053454, -0.03885704, -0.01730359,
          0.03279443,  0.02104167, -0.0036509 , -0.03248271,
          0.00658599,  0.01214667],
        [-0.03711472, -0.03053454, -0.03885704, -0.01730359,
          0.03279443,  0.02104167, -0.0036509 , -0.03248271,
          0.00658599,  0.01214667],
        [-0.03711472, -0.03053454, -0.03885704, -0.01730359,
          0.03279443,  0.02104167, -0.0036509 , -0.03248271,
          0.00658599,  0.01214667],
        [-0.03711472, -0.03053454, -0.03885704, -0.01730359,
          0.03279443,  0.02104167, -0.0036509 , -0.03248271,
          0.00658599,  0.01214667],
        [ 0.00190409,  0.01104267,  0.0230781 ,  0.02286566,
         -0.00604386,  0.02733138, -0.00492283,  0.02548278,
          0.02556369, -0.00648933],
        [-0.04445676,  0.02030777, -0.01786115, -0.00911763,
         -0.03881793,  0.02869422, -0.01748699, -0.00090595,
         -0.01381441, -0.02098224],
        [ 0.01318966, -0.02663804, -0.0314549 ,  0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 3914, 2091, 1835, 8363], dtype=int32)

In [29]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 503ms/step


array([[ 0.03082517, -0.04610357,  0.04222957,  0.03211014, -0.01077479,
         0.00309145, -0.04846605,  0.00188143,  0.00212694, -0.01327087],
       [ 0.03082517, -0.04610357,  0.04222957,  0.03211014, -0.01077479,
         0.00309145, -0.04846605,  0.00188143,  0.00212694, -0.01327087],
       [ 0.03082517, -0.04610357,  0.04222957,  0.03211014, -0.01077479,
         0.00309145, -0.04846605,  0.00188143,  0.00212694, -0.01327087],
       [ 0.03082517, -0.04610357,  0.04222957,  0.03211014, -0.01077479,
         0.00309145, -0.04846605,  0.00188143,  0.00212694, -0.01327087],
       [ 0.03509739, -0.00073775, -0.03137707, -0.00487087, -0.02460851,
        -0.00154037,  0.04263822,  0.02336605,  0.01397905, -0.01617285],
       [-0.01793668,  0.01097922, -0.0165213 ,  0.01807665, -0.02133367,
         0.02413776,  0.02171434,  0.03402725,  0.04512688, -0.04405539],
       [ 0.03836718,  0.00742186, -0.02175196, -0.0499684 ,  0.00043445,
         0.02875782, -0.04401061,  0.01876055